### ISSUE TITLE
cookie和邮箱都填了上去，依旧显示请输入邮箱和找不到cookie

### ISSUE THREAD

**Issue by 935714648** [ZhangYikaii/auto-buy-Python-tool#1]
Please confirm the email address: 935714648@qq.com
ERROR: Missing cookie.

**Comment by zhangyikaii** [comment]
您需要填在`Please fill out this document.txt`文件指定位置哦, 在单引号内.

**Comment by 935714648** [comment]
好的，谢谢您！
