### ISSUE TITLE
大佬，我这个提交订单后会一直重复

### ISSUE THREAD

**Issue by 982968** [ZhangYikaii/auto-buy-Python-tool#10]
![image](https://user-images.githubusercontent.com/38133470/74300024-7c549e00-4d89-11ea-8f0b-75c97bc01721.png)
大佬，我测试了一个有货的，会一直加入购物车并且不断提交订单，我看了一下订单，其中一个里面包含了两件商品

**Comment by 982968** [comment]
请问代码检测到有货并且提交后是不会停止监控的吗？ 现在基本都是每个ID限购一件口罩

**Comment by 982968** [comment]
只要检测到有货exe就会闪退🤣

**Comment by 982968** [comment]
还有 比如这个下架的商品（ID:17449572304） ,也会加入购物车然后报错闪退

**Comment by zhangyikaii** [comment]
提交失败之后是不会停止监控, 当时确实没有考虑到下架的商品, 对不起呀, 我下午或者晚上会修复一下, 谢谢你的issue啦! :joy:

**Comment by 982968** [comment]
哈哈，好的，加油大佬，等你的好消息👍

**Comment by HAISON2019** [comment]
购买数量那里修改？

**Comment by zhangyikaii** [comment]
你好呀, 我大概已经修复了下架和重复多次提交后不能停止的问题, 谢谢你呀! 现在可以下载最新版的了

**Comment by 982968** [comment]
![image](https://user-images.githubusercontent.com/38133470/74335089-5a353d00-4dd6-11ea-9b3a-a279921dcf71.png)
大佬，怎么一个订单数量是2个，一个是1个呢
