### ISSUE TITLE
收件地区编码怎么查

### ISSUE THREAD

**Issue by DJJ007** [ZhangYikaii/auto-buy-Python-tool#12]
大佬你好，我是一个超级小白，GitHub的图片我这查看不了，所以还是不知道怎么查收件地区编码，按了F12也没找到您所说的编码

**Comment by DJJ007** [comment]
请问是查看地区的元素代码吗？<div class="ui-area-text" data-id="19-1607-6736" title=

**Comment by zhangyikaii** [comment]
您好, 您加一下我QQ: 645064582我和你说吗? `19_1607_6736`这个地址编号是深圳市坪山新区的, 您看一下对不对呢

**Comment by fangshixiong** [comment]
https://blog.csdn.net/cyz52/article/details/104239558 参考这帖子里的教程，是用chrome按F12，再刷新一下，搜什么，那帖子里写得很详细，我已经学会了。

**Comment by ghost** [comment]
> 大佬你好，我是一个超级小白，GitHub的图片我这查看不了，所以还是不知道怎么查收件地区编码，按了F12也没找到您所说的编码

https://blog.csdn.net/cyz52/article/details/104239558 参考这帖子里的教程，是用chrome按F12，再刷新一下，搜什么，那帖子里写得很详细，我已经学会了。

**Comment by DJJ007** [comment]
> 您好, 您加一下我QQ: 645064582我和你说吗? `19_1607_6736`这个地址编号是深圳市坪山新区的, 您看一下对不对呢

对对对，所以这个就是了吗，谢谢大佬(*°∀°)=3

**Comment by DJJ007** [comment]
我科学上网了，现在能看到图片了，感谢

**Comment by zhangyikaii** [comment]
没事儿, 祝你身体健康哈!
