### ISSUE TITLE
感谢你的分享，期待给GUI版增加上购买商品数量功能

### ISSUE THREAD

**Issue by ghost** [ZhangYikaii/auto-buy-Python-tool#13]
买全棉时代的口罩，是1件商品2个，最多买5件商品。

所以需要修改一下下单数量。

再次感谢作者的分享，也呼吁大家口罩自用数量合理就好。

祝你新年快乐，身体健康。

**Comment by zhangyikaii** [comment]
好的, 过几天来, 也祝你新年快乐, 万事如意!
