### ISSUE TITLE
用京东APP扫描二维码无反应，用微信扫描后能登陆

### ISSUE THREAD

**Issue by ghost** [ZhangYikaii/auto-buy-Python-tool#14]
生成二维码后，直接用京东APP的扫一扫，对准二维码一直无响应。

然后换微信扫一扫，一扫就有反应了，网页打开后确实就能登录。

软件找了一个手机测试下单，全部正常。

**Comment by zhangyikaii** [comment]
嗯嗯 感谢, 我的也是, 京东APP有的时候又可以了[笑哭], 登录一次就行, 重启之后之间点开始监控就可以, 会记住并自动登录
