### ISSUE TITLE
3.0 GUI版本 ，第1次开始监控后停止。重新点开始后，查询结果重复的BUG

### ISSUE THREAD

**Issue by ghost** [ZhangYikaii/auto-buy-Python-tool#16]
我设置的查询速度是5秒一次。

开程序后，第一次点监控，第1次，第2次查询的结果都是每5秒返回。
--------------------------------------------------------------------------------------
Sun Feb 16 20:06:07 2020 > 验证登录状态...
Sun Feb 16 20:06:07 2020 > 第 1 次再尝试验证cookie...
Sun Feb 16 20:06:07 2020 > 正在尝试从历史讯息中恢复...
Sun Feb 16 20:06:08 2020 > 登录成功!
Sun Feb 16 20:06:08 2020 > 当前轮询速度为 5.000000 秒/次
Sun Feb 16 20:06:13 2020 > 第 1 次查询:
Sun Feb 16 20:06:13 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:18 2020 > 第 2 次查询:
Sun Feb 16 20:06:18 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:19 2020 > 已停止监控.
-----------------------------------------------------------------------------------

点停止，再点开始监控。每5秒刷新后，会返回连续查询几次的结果。
以后再停止，重新开始，这个BUG就一直有了。

一下的日志里，第26，27秒 返回了 第3次，第4次查询
第31秒 返回了 第5次，第6次查询
第35秒 返回了 第7次，第8次查询

不是每5秒一次。
-----------------------------------------------------------------------------------
Sun Feb 16 20:06:21 2020 > 验证登录状态...
Sun Feb 16 20:06:21 2020 > 登录成功!
Sun Feb 16 20:06:21 2020 > 当前轮询速度为 5.000000 秒/次
Sun Feb 16 20:06:26 2020 > 第 3 次查询:
Sun Feb 16 20:06:26 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:26 2020 > 第 4 次查询:
Sun Feb 16 20:06:27 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:31 2020 > 第 5 次查询:
Sun Feb 16 20:06:31 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:31 2020 > 第 6 次查询:
Sun Feb 16 20:06:32 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:36 2020 > 第 7 次查询:
Sun Feb 16 20:06:36 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:36 2020 > 第 8 次查询:
Sun Feb 16 20:06:37 2020 > 监控的 1 个商品无货.
Sun Feb 16 20:06:39 2020 > 已停止监控.
-----------------------------------------------------------------------------------

**Comment by zhangyikaii** [comment]
兄弟不好意思这个bug我也搞不太懂发生了什么[笑哭], 但是京东是不会卡查询次数的, 频率非常快都没关系的. 非常感谢你细致的测试, 请注意最近京东推出了一种先预约再抢购的方式, 这种方式会导致程序抢不到口罩

**Comment by ghost** [comment]
> 兄弟不好意思这个bug我也搞不太懂发生了什么[笑哭], 但是京东是不会卡查询次数的, 频率非常快都没关系的. 非常感谢你细致的测试, 请注意最近京东推出了一种先预约再抢购的方式, 这种方式会导致程序抢不到口罩

我测试了2天，测试的样本就是那个下午3点预约，晚上8点抢的口罩。都失败了。

感谢你。
