### ISSUE TITLE
执行完python JDAutoBuyTool.py没反应

### ISSUE THREAD

**Issue by xsharh** [ZhangYikaii/auto-buy-Python-tool#2]
执行完python JDAutoBuyTool.py没反应，直接这样
D:\py\auto-buy-Python-tool-master>python JDAutoBuyTool.py
D:\py\auto-buy-Python-tool-master>python JDAutoBuyTool.py

win10环境 Python 3.7.4

**Comment by zhangyikaii** [comment]
请问您已经执行了`pip install -r requirements.txt`并且按照`README.md`里的填写相应讯息了吗(小纠结)?

**Comment by xsharh** [comment]
我把链接和单引号分成两行了，合并在一行可以了。

**Comment by zhangyikaii** [comment]
好的
