### ISSUE TITLE
那个压缩包一直不能下载呢。

### ISSUE THREAD

**Issue by nutcrackers2** [ZhangYikaii/auto-buy-Python-tool#27]
下了一一点就断开了，然后就被禁止

**Comment by yk4399** [comment]
> 下了一一点就断开了，然后就被禁止

网的问题吧，用代理试试？

**Comment by nutcrackers2** [comment]
> > 下了一一点就断开了，然后就被禁止
> 
> 网的问题吧，用代理试试？

用了还是慢。断两次后就被服务器商禁止了。
。。在github下小文件还行。大的基本没有下来过。。
