### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by changhongWang** [ZhangYikaii/auto-buy-Python-tool#3]
![image](https://user-images.githubusercontent.com/18061091/74080383-7bb4c280-4a7e-11ea-996d-dd3e8c9c8803.png)

![image](https://user-images.githubusercontent.com/18061091/74080388-92f3b000-4a7e-11ea-87ee-8a817ccfdef1.png)

**Comment by zhangyikaii** [comment]
您的Python是3.6及其以上的吗[小纠结]
如果还是不行您可以试试今天发布的图形界面版本: https://github.com/ZhangYikaii/auto-buy-Python-tool/releases
