### ISSUE TITLE
请问有没有网盘的，这个我下载不下来。。。。

### ISSUE THREAD

**Issue by jocket1314** [ZhangYikaii/auto-buy-Python-tool#4]

**Comment by zhangyikaii** [comment]
链接：https://pan.baidu.com/s/1mFIg0zMwYN9c_JsLC9wFog 
提取码：8apw 
复制这段内容后打开百度网盘手机App，操作更方便哦

您的问题可能是GitHub在国内有些时候网速不行, 可以试试使用代理.
