### ISSUE TITLE
有货？无法提交订单

### ISSUE THREAD

**Issue by 0vvO** [ZhangYikaii/auto-buy-Python-tool#6]

**Comment by zhangyikaii** [comment]
请您截图报错信息, 很多人试了都可以, 下面是成功的截图:
![image](https://user-images.githubusercontent.com/46623714/74099713-8005dc00-4b61-11ea-8133-c47111bdcca6.png)
请您仔细阅读使用指南. 祝您身体健康

**Comment by 0vvO** [comment]
![OSO)P`@_3(FU7G7VLYB ONN](https://user-images.githubusercontent.com/33773085/74099844-d7f11280-4b62-11ea-9aba-e2b51f240741.png)

**Comment by zhangyikaii** [comment]
抱歉这可能是您的网络出现了抖动, 和程序无关.
请您稍安勿躁, 再次尝试.
